config/routes.rb
Rails.application.routes.draw do
  resources :registers

  devise_for :users, controllers: { registrations: "user/registrations" }
  resources :registers
  resources :courses
  resources :semesters

  root 'registers#index'

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  has_many :registers
  has_many :courses, through: :registers
  has_many :users, through: :registers
  validates :semester_name, presence: true,length: {maximum: 20}
  validates :semester_type, inclusion: {in: %w(Mandatory Optional),
      message: "%{value} is not a valid semester type. Must be 'Mandatory' or 'Optional'."}

end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_semester, only: [:show, :edit, :update, :destroy]
  before_action :student_restrict , restrict: [:new, :edit]

  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
    unless current_user.admin
      gpa= Register.joins(:user).joins(:semester).where('user_id = ?',current_user.id).pluck(:cgpa)
      gpa.delete(nil)
      @cgpa= gpa.inject(0){|sum,i| sum+i} / gpa.size
      @gpa= {}
      # @value=0;
      @semesters.each do |semester|
        temp=Register.joins(:user).joins(:semester).where('user_id = ? and semesters.semester_name=?',4,"#{semester.semester_name}").pluck(:cgpa)
        temp.delete(nil)
        as= temp.inject(0){|sum,i| sum+i} / temp.size if temp.present?
        @gpa[semester.semester_name] = as
      end
    end
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    def student_restrict

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:semester_name, :semester_type)
    end
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/_form.html.erb
<%= form_for(@semester) do |f| %>
  <% if @semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% @semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :semester_name %><br>
    <%= f.text_field :semester_name %>
  </div>
  <div class="field">
    <%= f.label :semester_type %><br>
    <%= f.text_field :semester_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing Semester</h1>

<%= render 'form' %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Semesters</h1>


<table>
  <thead>
    <tr>
      <th>Semester name</th>
      <th>Semester type</th>
      <% unless current_user.admin %>
        <th>Semester CGPA</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.semester_name %></td>
        <td><%= semester.semester_type %></td>
        <% unless current_user.admin %>
            <td><%= @gpa[semester.semester_name] %></td>
        <% end %>

        <% if current_user.admin %>
            <td><%= link_to 'Show', semester %></td>
            <td><%= link_to 'Edit', edit_semester_path(semester) %></td>
            <td><%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% unless current_user.admin %>
    <div>Your CGPA is <%= @cgpa %></div>
<% end %>
<br>

<% if current_user.admin %>

<%= link_to 'New Semester', new_semester_path %>

<% end %>

<%= link_to 'Go to Registration page', registers_path %>

app/views/semesters/new.html.erb
<h1>New Semester</h1>

<%= render 'form' %>

<%= link_to 'Back', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Semester name:</strong>
  <%= @semester.semester_name %>
</p>

<p>
  <strong>Semester type:</strong>
  <%= @semester.semester_type %>
</p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>