config/routes.rb
Rails.application.routes.draw do
  resources :registers

  devise_for :users, controllers: { registrations: "user/registrations" }
  resources :registers
  resources :courses
  resources :semesters

  root 'registers#index'

end

app/models/register.rb
class Register < ActiveRecord::Base
  validates :cgpa,allow_blank: true, :numericality => { :greater_than_or_equal_to => 0.00, :less_than_or_equal_to => 4.00 }, on: [:create, :update]
  validate :course_unique_for_each_user, on: :create
  belongs_to :course
  belongs_to :semester
  belongs_to :user

  private
  #Validating so that use can not register the same course twice.
  def course_unique_for_each_user
    number = Register.where('course_id = ? and user_id = ?', course_id, user_id).length
    if(number == 1)
      errors.add(:course_id, "is already registered.")
    end
  end

end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /registers
  # GET /registers.json
  def index
    if(current_user.admin)
      if params[:search]
        #@registers = Register.joins(:semester).where('semesters.semester_name LIKE ?', "%"+params[:search]+"%")|Register.joins(:course).where('courses.course_name LIKE ?', "%"+params[:search]+"%")
        @registers = Register.joins(:semester).where('semesters.semester_name LIKE ?',"%"+params[:search]+"%")|Register.joins(:user).where('users.email LIKE ?', "%"+params[:search]+"%")
        respond_to do |format|
          format.js {}
        end
      else
        @registers = Register.all
      end
    else
      if params[:search]
        @registers = Register.joins(:semester).where('user_id = ? and semesters.semester_name LIKE ?', current_user.id,"%"+params[:search]+"%")|Register.joins(:course).where('user_id=? and courses.course_name LIKE ?', current_user.id,"%"+params[:search]+"%")
        respond_to do |format|
          format.js {}
        end
      else
      @registers = Register.where(user_id: current_user.id)
      end

    end



  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)
    #@register = Register.find(id) || Register.new
    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:user_id, :course_id, :semester_id, :cgpa)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% unless current_user.admin %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
    <%end%>
    <% unless current_user.admin %>
        <div class="field">
          <%= f.label :course_id %><br>
          <%= f.select(:course_id,options_from_collection_for_select(Course.all, :id, :course_name))%>
        </div>

        <div class="field">
          <%= f.label :semester_id %><br>
          <%= f.select(:semester_id,options_from_collection_for_select(Semester.all, :id, :semester_name))%>
        </div>
    <%end%>

    <% if current_user.admin %>
        <div class="field">
          <%= f.label :cgpa %><br>
          <%= f.text_field :cgpa%>
        </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/registers/_register.html.erb
<tr>
  <td><%= register.course.course_name%></td>
  <td><%= register.semester.semester_name %></td>
  <td><%= register.user.email %></td>
  <td><%= register.cgpa %></td>
  <% if current_user.admin %>
      <td><%= link_to 'Edit', edit_register_path(register) %></td>
      <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <%end%>
</tr>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<p id="notice"><%= notice %></p>



<% if current_user.admin %>
    <h1>All the Registrations listed below:</h1>
    <%= form_tag registers_path, method: 'get',remote: true do %>
        <p>
          <%= text_field_tag :search, params[:search],placeholder: "Search by Semester name or Student email",size: 30%>
          <%= submit_tag "Search",name: nil %>
        </p>
    <% end %>
<% else %>
    <h1>Your Registered courses are listed below:</h1>
    <%= form_tag registers_path, method: 'get',remote: true do %>
        <p>
          <%= text_field_tag :search, params[:search],placeholder: "Search by Course or Semester name",size: 25%>
          <%= submit_tag "Search",name: nil %>
        </p>
    <% end %>
<% end %>


<table id="register_list">
  <thead>
    <tr>
      <th>Course name</th>
      <th>Registered in</th>
      <th>Registered by</th>
      <th>CGPA</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render(@registers)%>
  </tbody>
</table>

<br>

<%= link_to 'Register new courses', new_register_path %>
<div><%= link_to 'View semester history', semesters_path %></div>

app/views/registers/index.js.erb
$('#register_list tbody').html("<%= escape_javascript render(@registers) %>");
console.log('in the js page');

app/views/registers/new.html.erb
<h1>Register new courses</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>